name: Setup Biome
author: biomejs
description: Setup the Biome CLI in GitHub Actions
branding:
  color: yellow
  icon: terminal
inputs:
  token:
    description: GitHub Actions token to authenticate API requests
    required: true
    default: ${{ github.token }}
  version:
    description: The version of the Biome CLI to install
    required: true
    default: ""
  working-dir:
    description: The directory in which the action will look for lockfiles to extract the Biome version from
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.x.x

    - name: Install dependencies
      run: bun i
      shell: bash

    - name: Setup Biome
      run: bun .
      shell: bash
